travis:
  secure:
    BINSTAR_TOKEN: J5gQZUnHLEw+/+aQqvvNUD0Cyoj2RSgWYAe+VSaLDVnwelUxryvSIhuCQ3TgGRMlPjp9caafG9KevdGXCzoLFoyf86g/EdVZMivbs8IyyKtbX46cueepbmoqoqHSp7gaX/WDRbg37LU7chqTR39FF2q1ejhGhGYb5uWBs4RomHRezO9bj4js5orjlQWcO7qScydpfLOBKUdu5FZcnRz+fns7xuapiyfN3IYOAD/U704VPUzZBpb2nMyGyPvvV9dxRvVAyB3RzWurh7tybLz8h1Hhf/DbvbvXMd4LjfvVTze1vphbkEXtMFK7M9q4opBHnhB5kIz95ZZwyzTLcnXQ3A70F6iOXMxDlfjMP97SDVo4tKNZHcpyPmlh/MxGv15JhkI6uqcIg1xxdK655cIDVeHUeDv8yDfbFxrI8iU5Gpt9tNHGaWCaE7k5pX0ANhc4nZQK07J9f9RFQyKmhEMVifcoEwaCc4FdhXqwp08Pm31tUDRar5wIP0EMtzgumPyrhusqlEtW4CahWrO/gptlc+HC6Jx2/EB0yUcFMT2QYUj8+bURWi1FmYV5oawz3ZZsC4CyOSQkRqYOrdq6lDjxHa9RDHJTUc87RGIKc3xBlW411y4k0nX0KPM1m7lWQUnXqh099IIz7SCejEU51SvnAkDt7CqhQWkyj9gxXksqO5I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
